name: publish gh-pages
on:
  push:
    branches:
      - master
jobs:
  focus-build:
    runs-on: ubuntu-latest
    name: CoilPy publish gh-pages
    steps:
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx numpy

    - name: Generate html
      run: |
        cd ./docs
        make gh-pages