name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi, coilpy is under development. Please first check if you are using the latest version. You can update it by `pip install -U coilpy`.'
        pr-message: 'Please check if tests in GitHub actions are approved.'
